import {configureStore} from "@reduxjs/toolkit";
import cartslice from "./cartslice";


// store will contain  our slices slices
const store = configureStore(
    {
        reducer:{
            cart:cartslice,
        }
    }
)


export default store;

// cart: Refers to the slice of state that you're managing, identified by the name you gave it (cart in this case).
// cartReducer: Refers to the reducer function generated by createSlice, which handles updates to the cart slice of state based on defined actions.




